function runScriptFile(file)
	require(file)
end
runScriptFile("gameResource/script/objBase")
runScriptFile("gameResource/script/gameUtil/globalGameDefineEnum")
runScriptFile("gameResource/script/gameUtil/configReader")
runScriptFile("gameResource/script/gameUtil/globalFunction")
runScriptFile("gameResource/script/gameScene/firstScene")
runScriptFile("gameResource/script/gameScene/sceneManager")
runScriptFile("gameResource/script/gameScene/chooseRoleScene")
runScriptFile("gameResource/script/gameScene/gameScene")
runScriptFile("gameResource/script/gameUtil/entityManager")
objBase:instance()
globalFunction:instance()
firstScene:instance()
sceneManager:instance()
globalGameEnum:instance()
configReader:instance()
chooseRoleScene:instance()
entityManager:instance()
gameScene:instance()
function main()
	sceneManager:instance():changeSceneTo(sceneManager:instance():sceneFactory(globalGameEnum.SCENE_ENUM_FIRST_GAME_SCENE))
end
main()